# Generated by Django 6.1.1 on 2026-09-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ListingSafety',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('safety_anchor_time', models.DateTimeField()),
                ('anchor_type', models.CharField(max_length=255)),
                ('estimated_expiry', models.DateTimeField()),
                ('posted_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_index', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'listing_safety',
            },
        ),
        migrations.CreateModel(
            name='SafetyThreshold',
            fields=[
                ('threshold_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_category', models.CharField(max_length=50)),
                ('storage_type', models.CharField(max_length=50)),
                ('max_safe_hours', models.IntegerField()),
            ],
            options={
                'db_table': 'safety_threshold',
            },
        ),
        migrations.CreateModel(
            name='UnitMetrics',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'unit_metrics',
            },
        ),
        migrations.CreateModel(
            name='ListingCommerce',
            fields=[
                ('listing', models.OneToOneField(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='commerce', serialize=False, to='listings.listingsafety')),
                ('qty_available', models.IntegerField(default=0)),
                ('qty_reserved', models.IntegerField(default=0)),
                ('qty_sold', models.IntegerField(default=0)),
                ('orig_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floor_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('decay_interval', models.IntegerField(default=15)),
                ('pickup_deadline', models.DateTimeField()),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'db_table': 'listing_commerce',
            },
        ),
        migrations.CreateModel(
            name='PerishableProduct',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_desc', models.TextField(blank=True, null=True)),
                ('prod_type', models.CharField(blank=True, max_length=255, null=True)),
                ('image_path', models.CharField(max_length=255)),
                ('weight_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='listings.category')),
                ('merchant', models.ForeignKey(db_column='merch_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.merchant')),
                ('threshold', models.ForeignKey(db_column='threshold_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='listings.safetythreshold')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='listings.unitmetrics')),
            ],
            options={
                'db_table': 'perishable_product',
            },
        ),
        migrations.AddField(
            model_name='listingsafety',
            name='product',
            field=models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.CASCADE, related_name='safety_records', to='listings.perishableproduct'),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('ledger_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('qty_change', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='listings.listingcommerce')),
            ],
            options={
                'db_table': 'stock_ledger',
            },
        ),
    ]
