# Generated by Django 6.1.1 on 2026-09-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merch_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=255)),
                ('merch_type', models.CharField(max_length=50)),
                ('bus_permit_path', models.CharField(max_length=255)),
                ('bus_expiry_date', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('wallet_bal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'subscription_plan',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=255, unique=True)),
                ('user_pass', models.CharField(max_length=255)),
                ('user_role', models.CharField(max_length=50)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='MerchantContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_fullname', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('valid_id_path', models.TextField()),
                ('merchant', models.ForeignKey(db_column='merch_id', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.merchant')),
            ],
            options={
                'db_table': 'merchant_contact',
            },
        ),
        migrations.AddField(
            model_name='merchant',
            name='plan',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='accounts.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to='accounts.user'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_primary', models.BooleanField(default=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.user')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=255)),
                ('accreditation_path', models.CharField(max_length=255)),
                ('accreditation_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('total_food_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='food_bank_profile', to='accounts.user')),
            ],
            options={
                'db_table': 'food_bank',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('cons_id', models.AutoField(primary_key=True, serialize=False)),
                ('cons_fullname', models.CharField(max_length=255)),
                ('phone_num', models.CharField(blank=True, max_length=20, null=True)),
                ('total_food_saved', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='consumer_profile', to='accounts.user')),
            ],
            options={
                'db_table': 'consumer',
            },
        ),
        migrations.CreateModel(
            name='AccDeletionReq',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('time_requested', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='accounts.user')),
            ],
            options={
                'db_table': 'acc_deletion_req',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('ses_id', models.AutoField(primary_key=True, serialize=False)),
                ('ses_token', models.CharField(max_length=255)),
                ('ses_info', models.TextField(blank=True, null=True)),
                ('ses_login_time', models.DateTimeField(auto_now_add=True)),
                ('ses_logout_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.user')),
            ],
            options={
                'db_table': 'user_session',
            },
        ),
    ]
