# Generated by Django 6.1.1 on 2026-09-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='ocr_extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
