# Generated by Django 6.1.1 on 2026-09-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(default='Manual', max_length=255)),
                ('qty_donated', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('food_bank', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_donations', to='accounts.foodbank')),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='listings.listingcommerce')),
                ('merchant', models.ForeignKey(db_column='merch_id', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='accounts.merchant')),
            ],
            options={
                'db_table': 'donation',
            },
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('donation_req_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty_needed', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('food_bank', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='accounts.foodbank')),
                ('listing', models.ForeignKey(blank=True, db_column='listing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_requests', to='listings.listingcommerce')),
                ('merchant', models.ForeignKey(blank=True, db_column='merch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_donation_requests', to='accounts.merchant')),
            ],
            options={
                'db_table': 'donation_request',
            },
        ),
    ]
