# Generated by Django 6.1.1 on 2026-09-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReservation',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_qty', models.IntegerField()),
                ('order_status', models.CharField(default='Pending', max_length=255)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('downpayment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_voucher_code', models.CharField(max_length=255, unique=True)),
                ('rescued_weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consumer', models.ForeignKey(db_column='cons_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.consumer')),
                ('listing', models.ForeignKey(db_column='listing_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='listings.listingcommerce')),
            ],
            options={
                'db_table': 'order_reservation',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transac_id', models.AutoField(primary_key=True, serialize=False)),
                ('gateway_ref_id', models.CharField(max_length=255, unique=True)),
                ('transac_status', models.CharField(max_length=50)),
                ('commission_taken', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='transactions.orderreservation')),
            ],
            options={
                'db_table': 'payment_transaction',
            },
        ),
        migrations.CreateModel(
            name='RatingReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_score', models.IntegerField()),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('consumer', models.ForeignKey(db_column='cons_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.consumer')),
                ('surplus_listing', models.ForeignKey(db_column='surplus_list_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='listings.listingcommerce')),
            ],
            options={
                'db_table': 'rating_review',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalReq',
            fields=[
                ('withdrawal_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gcash_num', models.CharField(max_length=20)),
                ('withdrawal_status', models.CharField(default='Pending', max_length=50)),
                ('merchant', models.ForeignKey(db_column='merch_id', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='accounts.merchant')),
            ],
            options={
                'db_table': 'withdrawal_req',
            },
        ),
    ]
