# Generated by Django 6.1.1 on 2026-09-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('admin_notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_notif_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(blank=True, db_column='merch_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='accounts.merchant')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='accounts.user')),
                ('withdrawal', models.ForeignKey(blank=True, db_column='withdrawal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_notifications', to='transactions.withdrawalreq')),
            ],
            options={
                'db_table': 'admin_notification',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_audience', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='accounts.user')),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='accounts.user')),
            ],
            options={
                'db_table': 'user_notification',
            },
        ),
    ]
